apiVersion: v1
kind: Secret
metadata:
  name: registry-pull-secret
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |-
    {"auths":{"registry.secoder.net":{"username":"root1","password":"glpat-pgXR3B5I6zg1cbg0TaYaQG86MQp1OjUH.01.0w1th52q3","auth":"cm9vdDE6Z2xwYXQtcGdYUjNCNUk2emcxY2JnMFRhWWFRRzg2TVFwMU9qVUguMDEuMHcxdGg1MnEz"},"registry.t.secoder.net":{"username":"root1","password":"glpat-pgXR3B5I6zg1cbg0TaYaQG86MQp1OjUH.01.0w1th52q3","auth":"cm9vdDE6Z2xwYXQtcGdYUjNCNUk2emcxY2JnMFRhWWFRRzg2TVFwMU9qVUguMDEuMHcxdGg1MnEz"},"gitlab.t.secoder.net":{"username":"root1","password":"glpat-pgXR3B5I6zg1cbg0TaYaQG86MQp1OjUH.01.0w1th52q3","auth":"cm9vdDE6Z2xwYXQtcGdYUjNCNUk2emcxY2JnMFRhWWFRRzg2TVFwMU9qVUguMDEuMHcxdGg1MnEz"},"gitlab.t.secoder.net:5050":{"username":"root1","password":"glpat-pgXR3B5I6zg1cbg0TaYaQG86MQp1OjUH.01.0w1th52q3","auth":"cm9vdDE6Z2xwYXQtcGdYUjNCNUk2emcxY2JnMFRhWWFRRzg2TVFwMU9qVUguMDEuMHcxdGg1MnEz"}}}
